#!/usr/bin/python3
#
# Copyright (c) 2022 Jeff Doozan
#
# This is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

"""
print ignore data
"""

import pywikibot
import re

def main():

    import argparse
    argparser = argparse.ArgumentParser(description="Get ignore data from specified wiki page")
    argparser.add_argument("page", help="wiktionary page to get")
    args = argparser.parse_args()

    site = pywikibot.Site()
    page = pywikibot.Page(pywikibot.Link(args.page, site))
    text = page.text

    match = re.search(r"<!--IGNORE.*?\n(.*?)\s*-->", text, re.DOTALL)
    if not match:
        exit(1)

    print(match.group(1))

if __name__ == "__main__":
    main()
