#!/usr/bin/python3
#
# Copyright (c) 2021 Jeff Doozan
#
# This is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

"""
print links
"""

import pywikibot

def main():

    import argparse
    argparser = argparse.ArgumentParser(description="Get links from wiktionary page")
    argparser.add_argument("page", help="wiktionary page to get links from")
    args = argparser.parse_args()

    site = pywikibot.Site()
    page = pywikibot.Page(pywikibot.Link(args.page, site))
    links = [ page.title() for page in page.linkedPages() ]
#    links = [*{*links}]
    print("\n".join(links))

if __name__ == "__main__":
    main()

