#!/usr/bin/python3

import argparse

parser = argparse.ArgumentParser(description="Search language extract for articles matching a given pattern")
parser.add_argument('sortorder', help="file to use for sorting")
parser.add_argument("infile", help="file to sort")
parser.add_argument('--rank', help="print the sort rank", action='store_true')
args = parser.parse_args()

with open(args.sortorder) as infile:
    order = {k.rstrip():i for i,k in enumerate(infile)}

with open(args.infile) as infile:
    for line in sorted(infile.readlines(), key=lambda x: order.get(x.rstrip().split(":")[0], 99999999)):
        if args.rank:
            rank = order.get(line.rstrip().split(":")[0], 0)
            print(f"{rank} {line.rstrip()}")
        else:
            print(line.rstrip())
